#!/bin/sh -l

IMAGE="$INPUT_DOCKER_REGISTRY/$INPUT_DOCKER_REPO_NAME/$INPUT_DOCKER_IMAGE_NAME:$INPUT_DOCKER_IMAGE_TAG"

docker login $INPUT_DOCKER_REGISTRY -u $INPUT_DOCKER_USERNAME -p $INPUT_DOCKER_PASSWORD
docker build -t $IMAGE .
docker push $IMAGE

echo $IMAGE