#!/bin/sh -l

IMAGE="$INPUT_DOCKER_REGISTRY/$INPUT_DOCKER_REPO_NAME/$INPUT_DOCKER_IMAGE_NAME:$INPUT_DOCKER_IMAGE_TAG"
IMAGE_LATEST="$INPUT_DOCKER_REGISTRY/$INPUT_DOCKER_REPO_NAME/$INPUT_DOCKER_IMAGE_NAME:latest"

docker login $INPUT_DOCKER_REGISTRY -u $INPUT_DOCKER_USERNAME -p $INPUT_DOCKER_PASSWORD
docker build -t $IMAGE .

docker tag $IMAGE $IMAGE_LATEST

docker push $IMAGE
docker push $IMAGE_LATEST

echo '::set-output name=RESULT_IMAGE::$IMAGE'